# Generated by Django 5.1.15 on 2026-08-15 03:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FridgeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='app', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_name', models.CharField(default='Europe/Paris', max_length=64)),
                ('day_rollover_hour', models.PositiveSmallIntegerField(default=4)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('buddy_channel', models.CharField(blank=True, max_length=255)),
                ('buddy_disable_requested_at', models.DateTimeField(blank=True, null=True)),
                ('shards', models.IntegerField(default=0)),
                ('coach_quota_enabled', models.BooleanField(default=False, help_text="Contrainte sur le temps passé à développer le coach. Désactivée tant que le projet n'est pas fini.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('fridge', 'Frigo'), ('archived', 'Archivé')], default='active', max_length=16)),
                ('slot', models.PositiveSmallIntegerField(blank=True, help_text='1 à 3, ou vide', null=True)),
                ('color', models.CharField(default='#E8A33D', max_length=7)),
                ('emblem', models.CharField(default='◆', help_text='Glyphe affiché sur la jauge', max_length=8)),
                ('branch', models.CharField(blank=True, help_text="Branche de l'arbre de compétences", max_length=32)),
                ('is_coach_project', models.BooleanField(default=False)),
                ('weekly_commitment', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('slot', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('plancher', 'Plancher'), ('bonus', 'Bonus'), ('hebdo', 'Hebdomadaire')], max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('target', models.PositiveIntegerField(default=1)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('todo', 'À faire'), ('doing', 'En cours'), ('done', 'Fait')], default='todo', max_length=8)),
                ('estimated_sessions', models.PositiveSmallIntegerField(default=1)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='forge.project')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('accent', models.CharField(max_length=7)),
                ('baseline', models.CharField(blank=True, max_length=255)),
                ('modifier_key', models.CharField(blank=True, max_length=32)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('stake_shards', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('closed', 'Close'), ('paused', 'Pause')], default='running', max_length=16)),
                ('title_awarded', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-index',),
                'unique_together': {('user', 'index')},
            },
        ),
        migrations.CreateModel(
            name='SeasonBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('max_hp', models.PositiveIntegerField()),
                ('damage_taken', models.PositiveIntegerField(default=0)),
                ('regen', models.PositiveIntegerField(default=0, help_text='Vie récupérée lors des jours ratés')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='forge.season')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_day', models.DateField(db_index=True, help_text='Journée du coach, bascule à 4h')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_minutes', models.PositiveSmallIntegerField(default=25)),
                ('actual_minutes', models.PositiveSmallIntegerField(default=0)),
                ('mode', models.CharField(choices=[('normal', 'Normale'), ('degraded', 'Dégradée')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('done', 'Terminée'), ('abandoned', 'Abandonnée')], default='running', max_length=16)),
                ('rank_in_day', models.PositiveSmallIntegerField(default=1)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('xp_breakdown', models.JSONField(blank=True, default=dict)),
                ('focus_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, help_text='1 à 3', null=True)),
                ('verification', models.CharField(choices=[('server', 'Horodatée serveur'), ('unverified', 'Non vérifiée')], default='server', max_length=16)),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='forge.project')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='forge.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_note', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('next_action', models.CharField(blank=True, help_text="L'amorce : première action de la prochaine session", max_length=255)),
                ('source', models.CharField(default='manuel', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='forge.session')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = lundi')),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=25)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='forge.project')),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('atelier', 'Atelier'), ('corps', 'Corps')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kind')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='forge.track'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=48)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-unlocked_at',),
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DayWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = lundi')),
                ('start_time', models.TimeField(default=datetime.time(18, 0))),
                ('end_time', models.TimeField(default=datetime.time(23, 0))),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='forge.profile')),
            ],
            options={
                'ordering': ('weekday',),
                'unique_together': {('profile', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('planned_sessions', models.PositiveSmallIntegerField(default=3)),
                ('done_sessions', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='forge.project')),
            ],
            options={
                'ordering': ('-week_start',),
                'unique_together': {('project', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='RelaxWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_day', models.DateField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relax_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'coach_day')},
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forge.season')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('state', models.CharField(choices=[('validee', 'Validée'), ('ratee', 'Ratée'), ('neutre', 'Neutre')], max_length=8)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_statuses', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_statuses', to='forge.track')),
            ],
            options={
                'ordering': ('date',),
                'unique_together': {('user', 'track', 'date')},
            },
        ),
    ]
