# Generated by Django 5.1.15 on 2026-08-15 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_webhook',
            field=models.URLField(blank=True, help_text="Webhook d'un salon perso, canal de redondance"),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_minutes_before_end',
            field=models.PositiveSmallIntegerField(default=90, help_text='Le gardien se déclenche N minutes avant la fin de la fenêtre du soir'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pc', 'PC'), ('phone', 'Téléphone')], default='phone', max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('push_subscription', models.JSONField(blank=True, null=True)),
                ('paired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('coach_day', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'kind', 'coach_day')},
            },
        ),
    ]
