# Generated by Django 5.1.15 on 2026-08-15 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0002_remove_profile_telegram_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='kind',
            field=models.CharField(choices=[('atelier', 'Atelier'), ('corps', 'Corps'), ('entretien', 'Entretien')], max_length=16),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('anchor', models.CharField(choices=[('reveil', 'Au réveil'), ('apres_douche', 'Après la douche'), ('fin_de_session', 'En fin de session'), ('avant_coucher', 'Avant le coucher'), ('libre', 'Dans la journée')], default='libre', max_length=24)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Jours où elle est proposée, 0 = lundi. Vide = tous les jours.')),
                ('weekly_target', models.PositiveSmallIntegerField(default=6, help_text='Nombre de fois par semaine qui rend la semaine tenue')),
                ('reward_shards', models.PositiveSmallIntegerField(default=3)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='forge.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoutineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, help_text='Journée du coach, bascule à 4h')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('app', 'App'), ('telegram', 'Telegram'), ('agent', 'Agent')], default='app', max_length=16)),
                ('shards_awarded', models.PositiveSmallIntegerField(default=0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='forge.routine')),
            ],
            options={
                'ordering': ('-day', 'routine_id'),
                'unique_together': {('routine', 'day')},
            },
        ),
    ]
