# Generated by Django 5.1.15 on 2026-08-15 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0003_alter_track_kind_routine_routinecheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(choices=[('code', 'Code'), ('corps', 'Corps'), ('creatif', 'Créatif'), ('savoir', 'Savoir'), ('pratique', 'Pratique')], default='code', help_text='Deux slots au maximum par domaine (SPEC §4.3)', max_length=16),
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('weekly_budget', models.PositiveSmallIntegerField(default=2, help_text='Jours tolérés par semaine. Jamais zéro (SPEC §11.10).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GardeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, help_text='Journée du coach, bascule à 4h')),
                ('occurred', models.BooleanField(default=False, help_text='Le comportement a eu lieu ce jour-là')),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='forge.garde')),
            ],
            options={
                'ordering': ('-day', 'garde_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='garde',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_budget__gte', 1)), name='garde_budget_jamais_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='gardeday',
            unique_together={('garde', 'day')},
        ),
    ]
