# Generated by Django 5.1.15 on 2026-08-15 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0004_project_domain_garde_gardeday_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garde',
            name='auto_category',
            field=models.CharField(blank=True, choices=[('travail_projet', 'travail_projet'), ('travail_hors_projet', 'travail_hors_projet'), ('reseaux', 'reseaux'), ('scroll_passif', 'scroll_passif'), ('adulte', 'adulte'), ('jeu', 'jeu'), ('sport', 'sport'), ('autre', 'autre')], help_text='Catégorie de sonde qui marque cette garde. Vide = déclaration à la main seulement.', max_length=24),
        ),
        migrations.AddField(
            model_name='gardeday',
            name='origin',
            field=models.CharField(choices=[('main', 'Déclaré à la main'), ('sonde', 'Marqué par une sonde')], default='main', max_length=8),
        ),
        migrations.CreateModel(
            name='ProjectRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Chemin local du dépôt', max_length=500)),
                ('remote', models.CharField(blank=True, max_length=255)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='forge.project')),
            ],
            options={
                'unique_together': {('project', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agent', 'agent'), ('ext', 'ext'), ('mobile', 'mobile')], max_length=8)),
                ('category', models.CharField(choices=[('travail_projet', 'travail_projet'), ('travail_hors_projet', 'travail_hors_projet'), ('reseaux', 'reseaux'), ('scroll_passif', 'scroll_passif'), ('adulte', 'adulte'), ('jeu', 'jeu'), ('sport', 'sport'), ('autre', 'autre')], max_length=24)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('day', models.DateField(db_index=True, help_text='Journée du coach, bascule à 4h')),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-day', 'category'),
                'indexes': [models.Index(fields=['user', 'day', 'category'], name='forge_signa_user_id_204a17_idx')],
            },
        ),
    ]
