# Generated by Django 5.1.15 on 2026-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0006_probetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='verification',
            field=models.CharField(choices=[('git', 'Commits git'), ('fichiers', 'Fichiers modifiés'), ('premier_plan', 'Application au premier plan'), ('manuelle', 'Déclaration manuelle')], default='manuelle', help_text="Comment ce projet prouve qu'on a travaillé dessus (SPEC §6)", max_length=16),
        ),
    ]
