# Generated by Django 5.1.15 on 2026-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0007_project_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Début de la fenêtre observée, si la sonde sait la donner', null=True),
        ),
    ]
