# Generated by Django 5.1.15 on 2026-08-16 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0009_projectinterview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cosmetics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LootDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('rarity', models.CharField(max_length=16)),
                ('duplicate', models.BooleanField(default=False)),
                ('shards', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LootCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('rarity', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=16)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, help_text='niveau, semaine, saison', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-obtained_at',),
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OwnedRelic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('equipped', models.BooleanField(default=False)),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-obtained_at',),
                'unique_together': {('user', 'key')},
            },
        ),
    ]
