# Generated by Django 5.1.15 on 2026-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0010_profile_cosmetics_lootdraw_lootcard_ownedrelic'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='final_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='phantom_choice',
            field=models.CharField(choices=[('meilleure', 'Ta meilleure saison'), ('derniere', 'Ta dernière saison'), ('moyenne', 'La moyenne de tes saisons')], default='meilleure', max_length=16),
        ),
    ]
