# Generated by Django 5.1.15 on 2026-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0011_season_final_score_season_phantom_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='stake_forfeited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
