# Generated by Django 5.1.15 on 2026-08-17 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0012_season_stake_forfeited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('frigo', 'Jeter une idée au frigo'), ('vu', "Accuser réception d'un bilan"), ('reponse', 'Répondre à une question')], max_length=8)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('answer', models.TextField(blank=True)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('uses', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
