# Generated by Django 5.1.15 on 2026-08-17 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0013_actionlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_base_url',
            field=models.URLField(blank=True, help_text="Adresse par laquelle un lien signé est joignable de l'extérieur (§11.7). Sans elle, le bilan part sans son bouton « vu » : mieux vaut pas de lien qu'un lien vers 127.0.0.1, qui ne mène nulle part chez l'ami."),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Lundi de la semaine couverte')),
                ('body', models.TextField()),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start',),
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
