# Generated by Django 5.1.15 on 2026-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0014_profile_public_base_url_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='doing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
