# Generated by Django 5.1.15 on 2026-08-17 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0016_weeklyreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_early_at', models.DateTimeField(blank=True, null=True)),
                ('days_given_back', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiatuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-starts_on',),
            },
        ),
    ]
