# Generated by Django 5.1.15 on 2026-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0017_hiatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='morning_hour',
            field=models.PositiveSmallIntegerField(blank=True, default=8, help_text="Heure du rappel du matin, qui redit l'amorce laissée hier soir. Vide : pas de rappel. C'est le déclencheur le moins cher du système — l'idée travaille toute la journée au lieu d'être découverte à 21h.", null=True),
        ),
    ]
