# Generated by Django 5.2.17 on 2026-08-18 01:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge", "0018_profile_morning_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("reason", models.CharField(max_length=200)),
                (
                    "declared_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="forge.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-starts_on",),
            },
        ),
    ]
