# Generated by Django 5.2.17 on 2026-08-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge", "0019_projecthold"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="contract_projects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="season",
            name="contract_sessions_per_week",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="season",
            name="contract_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
