# Generated by Django 5.2.17 on 2026-08-18 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge", "0020_season_contract_projects_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ConversationTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Toi"), ("assistant", "L'assistant")],
                        max_length=12,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="forge.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProposedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=48)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("summary", models.CharField(max_length=255)),
                ("before", models.TextField(blank=True)),
                ("after", models.TextField(blank=True)),
                ("warning", models.CharField(blank=True, max_length=255)),
                ("empreinte", models.CharField(blank=True, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("attente", "En attente"),
                            ("appliquee", "Appliquée"),
                            ("ecartee", "Écartée"),
                            ("perimee", "Périmée"),
                        ],
                        default="attente",
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="forge.conversationturn",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
