# Generated by Django 5.2.17 on 2026-08-18 08:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge", "0021_conversation_conversationturn_proposedaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ascendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_index",
                    models.PositiveSmallIntegerField(
                        help_text="1 pour la première année"
                    ),
                ),
                (
                    "closed_on",
                    models.DateField(
                        help_text="Journée du coach où l'année a été close"
                    ),
                ),
                ("closed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "voie",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ampleur", "Ampleur"),
                            ("exigence", "Exigence"),
                            ("memoire", "Mémoire"),
                            ("echo", "Écho"),
                            ("serment", "Serment"),
                        ],
                        help_text="Choisie après la clôture. Vide tant que le choix n'est pas fait.",
                        max_length=16,
                    ),
                ),
                ("title_awarded", models.CharField(blank=True, max_length=120)),
                ("seasons_closed", models.PositiveSmallIntegerField(default=0)),
                ("bosses_killed", models.PositiveSmallIntegerField(default=0)),
                ("minutes", models.PositiveIntegerField(default=0)),
                ("xp_at_reset", models.PositiveIntegerField(default=0)),
                ("level_at_reset", models.PositiveSmallIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ascendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-year_index",),
                "unique_together": {("user", "year_index")},
            },
        ),
    ]
