# Generated by Django 5.2.17 on 2026-08-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge", "0022_ascendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="ascendance",
            name="rank_at_reset",
            field=models.CharField(default="F", max_length=2),
        ),
        migrations.AddField(
            model_name="ascendance",
            name="slots_engraved",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="ascendance",
            name="voie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ampleur", "Ampleur"),
                    ("exigence", "Exigence"),
                    ("memoire", "Mémoire"),
                    ("echo", "Écho"),
                    ("forge", "Forge"),
                    ("serment", "Serment"),
                ],
                help_text="Choisie après la clôture. Vide tant que le choix n'est pas fait.",
                max_length=16,
            ),
        ),
    ]
