# Generated by Django 6.1 on 2026-08-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0023_ascendance_rank_at_reset_ascendance_slots_engraved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frame',
            field=models.TextField(blank=True, help_text='Ce qui borne le projet : légalité, budget, matériel'),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, help_text='La condition de fin du projet (SPEC §4.5)'),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='exit_criterion',
            field=models.CharField(blank=True, help_text="À quoi on sait que c'est fini", max_length=500),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='load',
            field=models.CharField(blank=True, help_text='La charge estimée, en toutes lettres : « 6–8 h »', max_length=64),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='resource',
            field=models.CharField(blank=True, help_text='Le support précis : cours, dépôt, chapitre', max_length=255),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='scope',
            field=models.CharField(blank=True, help_text="Ce que l'étape couvre, et ce qu'elle laisse", max_length=255),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='DiscardedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecartees', to='forge.project')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('outcome', models.CharField(blank=True, help_text="Ce qu'on sait faire à la sortie du bloc", max_length=500)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('load', models.CharField(blank=True, max_length=64)),
                ('cost', models.CharField(blank=True, max_length=64)),
                ('optional', models.BooleanField(default=False)),
                ('exit_criterion', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='forge.project')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
