# Generated by Django 6.1 on 2026-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0024_project_frame_project_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='deadline',
            field=models.TimeField(blank=True, help_text="Heure limite, heure locale. Vide : la routine n'en a pas.", null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='direction',
            field=models.CharField(choices=[('avant', "Avant l'heure"), ('apres', "Après l'heure")], default='avant', max_length=8),
        ),
        migrations.AddField(
            model_name='routinecheck',
            name='on_time',
            field=models.BooleanField(default=True),
        ),
    ]
