# Generated by Django 6.1 on 2026-08-19 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0026_ponctuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 trop facile, 2 juste, 3 trop dur', null=True),
        ),
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.CharField(help_text='Ce qui a été constaté, en toutes lettres', max_length=500)),
                ('obtained_on', models.DateField(help_text='Journée du coach où elle a été constatée')),
                ('shards_awarded', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves', to='forge.projectbloc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='forge.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-obtained_on', '-id'),
            },
        ),
    ]
