# Generated by Django 6.1 on 2026-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0027_session_difficulty_preuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='extensions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Combien de fois la séance a été prolongée'),
        ),
    ]
