# Generated by Django 6.1 on 2026-08-19 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0028_session_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlink',
            name='kind',
            field=models.CharField(choices=[('frigo', 'Jeter une idée au frigo'), ('vu', "Accuser réception d'un bilan"), ('reponse', 'Répondre à une question'), ('demarrer', 'Démarrer la séance proposée'), ('reporter', 'Reporter le gardien')], max_length=8),
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_at',),
            },
        ),
    ]
