# Generated by Django 6.1 on 2026-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0029_alter_actionlink_kind_rappel'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
