# Generated by Django 6.1 on 2026-08-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0030_season_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='reussie',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='voie',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
