# Generated by Django 6.1 on 2026-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0031_season_reussie_season_voie'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='minutes_done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
