# Generated by Django 6.1 on 2026-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0032_roadmapstep_minutes_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='plan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
