# Generated by Django 6.1 on 2026-08-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0033_session_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbloc',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='forge.projectbloc'),
        ),
    ]
