# Generated by Django 6.1 on 2026-09-16 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0034_projectbloc_done_at_roadmapstep_bloc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuffActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('effect', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0)),
                ('day', models.DateField()),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-activated_at',),
                'indexes': [models.Index(fields=['user', 'day', 'effect'], name='forge_buffa_user_id_f9394b_idx')],
            },
        ),
    ]
