# Generated by Django 6.1 on 2026-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0035_buffactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='horizon',
            field=models.CharField(choices=[('long', 'Long cours'), ('court', 'Court terme')], default='court', help_text='Étiquette de lecture, sans effet sur aucune règle', max_length=8),
        ),
    ]
