# Generated by Django 6.1 on 2026-09-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0036_project_horizon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='horizon',
            field=models.CharField(choices=[('long', 'Projet long'), ('court', 'Projet court')], default='court', help_text='Étiquette de lecture, sans effet sur aucune règle', max_length=8),
        ),
    ]
